name: Publicar descuentos en Twitter

on:
  schedule:
    - cron: '0 13 * * *'   # todos los días a las 13:00 UTC (10 AM en Argentina)
  workflow_dispatch:        # permite ejecutarlo manualmente desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo .env
        run: |
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_KEY_SECRET=${{ secrets.TWITTER_API_KEY_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env

      - name: Ejecutar bot
        run: python main.py